language: sh
sudo: required
services:
  - docker

script: windows/build.sh

deploy:
  provider: s3
  access_key_id: AKIAJ7GTIETKB42Y42PA
  secret_access_key:
    secure: S/auQL+AvFz3CHDnbDoFc289LKwr70kkHkWfS33hva8J7U18NEux3YTM6yLFT+89m1FyaTBywNyg7hDV+Z1jlM48fvn/Qb4pPQx8Q7hZpdjZodMjDlPU276xzNAfM8GEktP8vDkO6UDvLKbkTZfn5xwl+R0eVIr55Tx3XSaW62fS4eoKugiKM6k/QMfj/lwFMStDFSa2s7YCubxVdAr2dF8qF8JPfLMCOicEZkLoIgoqhTEZ6Mv7X7VQpm+yXbB8NIEK1SOt6S2yOKIg2kdU7SEyDhJYJUM3GxB+GxGa1gBoDQ7e8A4MD5w9wqr84hoqCJ8hpiaeqR3lj6oMcVk0fb/X5ACB7FMFszJT+uVPLlOPeDfGOO6oDWm+KmwBo1pblDP6eAvxzLwqD9FkYohscASHjoLHZ3qAES5J6eB/gPnpWg5FPUrJbKU7dbT58DgsECM/agsiUJK/pkYgiGYx5+XfOWunBeHUXH57rKixnwX52uvaGr3A4ttjWQXTfV08uyIAfrxwzZwFH31jOdqfH2WioYU4Y586ugcRJe0fzw953HsmNAMfI6dCCUK5Q4fsrfOg5JV7lAdQQHAbYG9AgVS3xnLIYvVSsMKMT2D8fM863DSgUlvRvPlGC4rgAF1juuIffupVAwbqI0aqWXzRbzwC87GOdw4qHRbBLkgGINQ=
  bucket: fll-scoring-launcher
  local-dir: dist
  acl: public_read
  on:
    repo: 2roy999/fll-launcher
    branch: master
